server:
  port: 8001

spring:
  datasource:
    # url: jdbc:mysql://127.0.0.1:3306/meeting?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&
    url: jdbc:mysql://121.40.95.78:3306/meeting?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&
    username: root
    # password: 123456
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    # 出现异常时，直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    # 不要为工程中的资源文件建立映射
    add-mappings: false

mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml
  type-aliases-package: com.meeting.entity

file:
  # 本地测试
  # path: "D:/www/meeting"
  path: "/www/meeting"

picture:
  reg: .+(.jpeg|.jpg|.png)$