server:
  port: 8443
  ssl:
    key-store: classpath:ssl.pfx
    key-store-password: 123456
    enabled: true
    key-store-type: PKCS12
  max-http-header-size: 16384

router:
  services:
    - serviceName: login_and_register
      path: /login_and_register
      ip:
        - http://127.0.0.1:8000
    - serviceName: file
      path: /file
      ip:
        - http://127.0.0.1:8001
    - serviceName: chat
      path: /chat
      ip:
        - http://127.0.0.1:8005