server:
  port: 8443
  ssl:
    key-store: classpath:ssl.pfx
    key-store-password: 123456
    enabled: true
    key-store-type: PKCS12
  max-http-header-size: 16384

logging:
  config: classpath:log4j2.xml

router:
  services:
    - serviceName: login_and_register
      path: /login_and_register
      ip:
        - http://127.0.0.1:8000
    - serviceName: file
      path: /file
      ip:
        - http://127.0.0.1:8001
    - serviceName: chat
      path: /chat
      ip:
        - http://127.0.0.1:8005
    - serviceName: meeting
      path: /meeting
      ip:
        - http://121.40.95.78:4000
    - serviceName: test
      path: /test
      ip:
        - http://127.0.0.1:8900
        - http://127.0.0.1:8901